runtime: python39  # You can change this depending on the Python version you need
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "aviato-444212-e844e18fb8d1.json"  # If needed

instance_class: F2  # Optional: You can change this to the instance class you need
